export enum ComplaintType {
  AgriculturaEAgroecologia = 'Agricultura e Agroecologia',
  CartaDeServicos = 'Carta de Serviços',
  CienciaETecnologia = 'Ciência e Tecnologia',
  ComercioEServicos = 'Comércio e Serviços',
  ComissaoPermanenteDeLicitacaoCPL = 'Comissão Permanente de Licitação - CPL',
  Comunicacoes = 'Comunicações',
  Cultura = 'Cultura',
  DesportoELazer = 'Desporto e Lazer',
  DireitosDeCidadania = 'Direitos de Cidadania',
  Energia = 'Energia',
  Estradas = 'Estradas',
  Habilitacao = 'Habilitação',
  Industria = 'Indústria',
  LeiGeralDeProtecaoDeDadosLGPD = 'Lei Geral de Proteção de Dados - LGPD',
  OrganizacaoAgraria = 'Organização Agrária',
  Ouvidoria = 'Ouvidoria',
  PrevidenciaSocial = 'Previdência Social',
  RecursosHumanos = 'Recursos Humanos',
  Saneamento = 'Saneamento',
  Saude = 'Saúde',
  Trabalho = 'Trabalho',
  Transporte = 'Transporte',
  Urbanismo = 'Urbanismo',
}
